{% set name = "fblog" %}
{% set version = "4.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brocode/fblog/archive/v{{ version }}.tar.gz
  sha256: 0212dd590cdcb4794a44ea79535ba298c1e971bb344a248fb84528777b0998f1

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - fblog --help

about:
  home: https://github.com/brocode/fblog
  license: WTFPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Small command-line JSON log viewer
  dev_url: https://github.com/brocode/fblog

extra:
  recipe-maintainers:
    - danielnachun
