{% set name = "fblog" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brocode/fblog/archive/v{{ version }}.tar.gz
  sha256: 1bf50a4b7f1775dba0bacfb5e7709baf8abebd3e4cca2f728a1976950b0d2a2e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - fblog --help

about:
  home: https://github.com/brocode/fblog
  license: WTFPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Small command-line JSON log viewer
  dev_url: https://github.com/brocode/fblog

extra:
  recipe-maintainers:
    - danielnachun
