{% set name = "fblog" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brocode/fblog/archive/v{{ version }}.tar.gz
  sha256: d4a25cdc27cd540b352b0515343f0100b0585712b7c4e5d9c8cd4afa1cbb9f91

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - fblog --help

about:
  home: https://github.com/brocode/fblog
  license: WTFPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Small command-line JSON log viewer
  dev_url: https://github.com/brocode/fblog

extra:
  recipe-maintainers:
    - danielnachun
