context:
  version: "4.16.0"

package:
  name: fblog
  version: ${{ version }}

source:
  url: https://github.com/brocode/fblog/archive/v${{ version }}.tar.gz
  sha256: 061288675d40ca9b70c8e3e0508f09ddee70b8a09f25c7b8ef2dbd6406d4e213

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - fblog --help

about:
  license: WTFPL
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Small command-line JSON log viewer
  homepage: https://github.com/brocode/fblog
  repository: https://github.com/brocode/fblog

extra:
  recipe-maintainers:
    - danielnachun
